name: Verify Maven Build Caching Samples

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  enable-env-var:
    name: Enable Develocity with env var
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}
      DEVELOCITY_ENABLED: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package -B
  disable-env-var:
    name: Explicitly disable Develocity with env var
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}
      DEVELOCITY_ENABLED: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package -B
  enable-cmdline:
    name: Enable Develocity with command line
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package -B -Ddevelocity.enabled=true
  no-env-var:
    name: No env var, but access key is set up
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package -B
  no-env-var-no-access-key:
    name: No env var, no access key
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package -B
  enable-env-var-no-access-key:
    name: Enable Develocity with env var, access key missing
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_ENABLED: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package -B